books/urls.py
from django.urls import path, include
from .views import BookListview, BookDetialView

app_name = "books"
urlpatterns = [
    path('',BookListview.as_view(), name='book_list'),
    path('<int:id>/',BookDetialView.as_view(), name="detial"),
    path('users/', include('users.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import LandingPageView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', LandingPageView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    # costom url
    path('users/',include('users.urls')),
    path('books/',include('books.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import Registration, Login, ProfileViev, LogoutView, ProfileUpdateView


app_name = "users"

urlpatterns = [
    path('signup/', Registration.as_view(), name = 'register'),
    path('signin/', Login.as_view(), name = 'login'),
    path('profile/', ProfileViev.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name="profile_edit"),
    path('logout/', LogoutView.as_view(), name='logout'),
]

books/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import CustomUser


# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)

    def __str__(self) -> str:
        return self.title
    

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    CustomUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    def __str__(self) -> str:
        return f"{self.stars_given} stars for {self.CustomUser.CustomUsername} {self.CustomUser.last_name}: {self.book.title} "

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default='user-profile.png')

users/forms.py
from django  import forms
from users.models import CustomUser

class UserCreateForms(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username','email','first_name','last_name','password']

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        
        return user

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username','email','first_name','last_name','profile_picture']


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=128)

books/views.py
from django.views import View
from django.shortcuts import render
from .models import Book
# Create your views here.

class BookListview(View):
    def get(self, request):
        books = Book.objects.all()
        return render(request, "books/books.html",{'books':books})
    

class BookDetialView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        context = {
            'book' : book
        }
        return render(request, "books/detial.html", context)

config/views.py
from django.views import View
from django.shortcuts import render


class LandingPageView(View):
    def get(self, request):
        return render(request, "landing.html")

users/views.py
from django.shortcuts import redirect, render
from django.views import View
from . forms import UserCreateForms, UserUpdateForm
from users.models import CustomUser
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import login, logout
from django.contrib import messages
# Create your views here.


class Registration(View):
    def get(self, request):
        forms = UserCreateForms()
        context = {
            'form' : forms,
        }
        return render(request, 'users/register.html', context)
    
    def post(self, request):
        create_form = UserCreateForms(data=request.POST)
        
        if create_form.is_valid():
            create_form.save()

            return redirect('users:login')
        else:
            context = {
                'form' : create_form,
            }
            return render(request, 'users/register.html', context)


class Login(View):

    def get(self, request):
        forms = AuthenticationForm()
        return render(request, 'users/login.html', {'login_form': forms})
    
    def post(self, request):
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            # logged in the user
            user  = form.get_user()
            login(request, user)
            messages.success(request, "Logged in")
            return redirect("books:book_list")
        else:
            return render(request, 'users/login.html', {'login_form': form})
        
class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You sucsessfully logged out ...')
        return redirect('home')
        

class ProfileViev(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        # if not user.is_authenticated:
        #     return redirect('users:login')
        return render(request, 'users/profile.html', {'user' : user})


class ProfileUpdateView(LoginRequiredMixin ,View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, 'users/profile_edit.html',{'form' : user_update_form})
    
    def post(self, request):
        user_update_data = UserUpdateForm(instance=request.user, 
                                          data=request.POST,
                                          files=request.FILES
        )

        if user_update_data.is_valid():
            user_update_data.save()
            messages.success(request , "Profile succsessfuly changes!")
            return redirect('users:profile')
        
        return render(request , "users/profile_edit.html", {'form':user_update_data})

books/templates/books/books.html
{%extends "base.html"%}
{%block title%}Books Page{%endblock%}

{%block content%}
    <h1>Books</h1>
        {% for book in books %}
        <ul>
            <a href="{% url 'books:detial' book.id %}"><li>{{ book.title }}</li></a>
            <p>{{ book.description }}</p>
        </ul>
        {% endfor%}
{%endblock%}

books/templates/books/detial.html
{%extends "base.html"%}
{%block title%}Detial{%endblock%}
{%block content%}
    <h1>Detial page</h1>
    <h3>{{book.title}}</h3>
    <p>
        {{book.description}}
    </p>
{%endblock%}

templates/base.html
{% load static %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css">
    <title>{% block title %} Goodreads {% endblock %}</title>
</head>
<body>
<div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home'%}">Goodreads</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'books:book_list' %}">Books</a>
                  </li>
                  <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li> -->
                </ul>
                <div class="me-5">
                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{request.user.username}}
                            </a>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                        </ul>
                    {%else%}
                        <a class="btn btn-primary" href="{% url 'users:login' %}">login</a>
                    {%endif%}
                </div>
                <!-- <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->

              </div>
            </div>
          </nav>

            {% if messages %}
                {%for message in messages%}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{message}}
                </div>
                {%endfor%}
            {%endif%}
    
    {%block content%}
     <!-- har bir page uchun joy -->
    {%endblock%}
    

</div>
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

templates/landing.html
{%extends "base.html"%}
{%block content%}
    <h1>landing page</h1>

    <p>
        Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]
    </p>
{%endblock%}

users/templates/users/login.html
{%extends "base.html"%}
{%block title%}login{%endblock%}
{%block content%}
    <h1>login page</h1>
    <form method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        
        <button class="btn btn-success" type="submit">login</button>
        <a class="btn" href="{% url 'users:register' %}">create account</a>
    </form>

{%endblock%}

users/templates/users/profile.html
{%extends "base.html"%}
{%block title%}Profile{%endblock%}
{%block content%}
    <h1>Profile page</h1>

    <img class="user_profile" src="{{user.profile_picture.url}}" alt="avatar">
    <p>User name: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>email: {{ user.email }}</p>
    <a href="{% url 'users:profile_edit'%}">settings</a>
{%endblock%}

users/templates/users/profile_edit.html
{%extends 'base.html'%}

{%block content%}
    <h1>Profile update</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">save</button>
    </form>
{%endblock%}

users/templates/users/register.html
{%extends "base.html"%}
{%block title%}registration{%endblock%}
{%block content%}
    <h1>registration page</h1>

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" >Next</button>
    </form>
{%endblock%}